export const TAG_TAXONOMY = {
  geographie: {
    littoral: {
      label: "Littoral",
      family: "geographie",
      weight: "standard",
      description: "Territoire situé au contact direct de la mer ou de l'océan.",
      status: "active",
    },
    maritime: {
      label: "Maritime",
      family: "geographie",
      weight: "standard",
      description: "Imaginaire, usages ou paysages liés à la mer.",
      status: "active",
    },
    montagne: {
      label: "Montagne",
      family: "geographie",
      weight: "standard",
      description: "Reliefs montagnards, massifs et hautes vallées.",
      status: "active",
    },
    volcanique: {
      label: "Volcanique",
      family: "geographie",
      weight: "precise",
      description: "Paysages, sols ou reliefs issus d'une histoire volcanique.",
      status: "active",
    },
    mineral: {
      label: "Minéral",
      family: "geographie",
      weight: "precise",
      description: "Présence forte de pierre, roche, relief nu ou matière minérale.",
      status: "active",
    },
    falaises: {
      label: "Falaises",
      family: "geographie",
      weight: "precise",
      description: "Escarpements, caps, gorges ou fronts rocheux marqués.",
      status: "active",
    },
    mediterraneen: {
      label: "Méditerranéen",
      family: "geographie",
      weight: "standard",
      description: "Climat, paysages ou culture de bord méditerranéen.",
      status: "active",
    },
    insulaire: {
      label: "Insulaire",
      family: "geographie",
      weight: "precise",
      description: "Territoire dont l'identité est structurée par l'île.",
      status: "candidate",
    },
    tropical: {
      label: "Tropical",
      family: "geographie",
      weight: "precise",
      description: "Climat, végétation ou paysages tropicaux.",
      status: "candidate",
    },
    lagon: {
      label: "Lagon",
      family: "geographie",
      weight: "rare",
      description: "Espace maritime abrité par récif ou barrière corallienne.",
      status: "candidate",
    },
    recifal: {
      label: "Récifal",
      family: "geographie",
      weight: "rare",
      description: "Milieux de récifs, coraux ou barrières marines.",
      status: "candidate",
    },
    mangrove: {
      label: "Mangrove",
      family: "geographie",
      weight: "rare",
      description: "Forêt littorale tropicale liée aux eaux saumâtres.",
      status: "candidate",
    },
    amazonien: {
      label: "Amazonien",
      family: "geographie",
      weight: "rare",
      description: "Milieux forestiers et fluviaux de l'espace amazonien.",
      status: "candidate",
    },
    equatorial: {
      label: "Équatorial",
      family: "geographie",
      weight: "rare",
      description: "Climat chaud et humide des territoires proches de l'équateur.",
      status: "candidate",
    },
    forestier: {
      label: "Forestier",
      family: "geographie",
      weight: "standard",
      description: "Territoire fortement marqué par les forêts.",
      status: "candidate",
    },
    fluvial: {
      label: "Fluvial",
      family: "geographie",
      weight: "standard",
      description: "Paysages ou usages structurés par fleuves, rivières ou canaux.",
      status: "candidate",
    },
    marais: {
      label: "Marais",
      family: "geographie",
      weight: "precise",
      description: "Zones humides, marais, tourbières ou paysages amphibies.",
      status: "candidate",
    },
    plateau: {
      label: "Plateau",
      family: "geographie",
      weight: "standard",
      description: "Hautes terres, causses ou plateaux ouverts.",
      status: "candidate",
    },
    vallee: {
      label: "Vallée",
      family: "geographie",
      weight: "standard",
      description: "Territoire organisé autour d'une vallée marquée.",
      status: "candidate",
    },
    bocage: {
      label: "Bocage",
      family: "geographie",
      weight: "precise",
      description: "Paysage rural de haies, prairies et petites parcelles.",
      status: "candidate",
    },
    steppe: {
      label: "Steppe",
      family: "geographie",
      weight: "rare",
      description: "Paysage ouvert, sec, pauvre en arbres, à forte horizontalité.",
      status: "candidate",
    },
    haute_montagne: {
      label: "Haute montagne",
      family: "geographie",
      weight: "precise",
      description: "Relief alpin ou pyrénéen d'altitude, glaciaire ou très vertical.",
      status: "candidate",
    },
  },

  patrimoine: {
    patrimoine: {
      label: "Patrimoine",
      family: "patrimoine",
      weight: "generic",
      description: "Marqueur patrimonial général, à préciser si possible.",
      status: "active",
    },
    architecture: {
      label: "Architecture",
      family: "patrimoine",
      weight: "generic",
      description: "Bâti remarquable ou identité architecturale large.",
      status: "active",
    },
    medieval: {
      label: "Médiéval",
      family: "patrimoine",
      weight: "standard",
      description: "Châteaux, remparts, villages ou héritages du Moyen Âge.",
      status: "active",
    },
    monumental: {
      label: "Monumental",
      family: "patrimoine",
      weight: "standard",
      description: "Bâti de grande échelle ou présence visuelle imposante.",
      status: "active",
    },
    brutaliste: {
      label: "Brutaliste",
      family: "patrimoine",
      weight: "precise",
      description: "Architecture de béton, formes massives ou modernité publique.",
      status: "active",
    },
    phares: {
      label: "Phares",
      family: "patrimoine",
      weight: "precise",
      description: "Phares, feux maritimes et repères du littoral.",
      status: "active",
    },
    villages: {
      label: "Villages",
      family: "patrimoine",
      weight: "standard",
      description: "Villages remarquables, bourgs anciens ou silhouettes rurales.",
      status: "active",
    },
    religieux: {
      label: "Religieux",
      family: "patrimoine",
      weight: "standard",
      description: "Abbayes, églises, sanctuaires ou patrimoine spirituel.",
      status: "candidate",
    },
    militaire: {
      label: "Militaire",
      family: "patrimoine",
      weight: "standard",
      description: "Fortifications, citadelles, lignes défensives ou sites stratégiques.",
      status: "candidate",
    },
    antique: {
      label: "Antique",
      family: "patrimoine",
      weight: "precise",
      description: "Vestiges, monuments ou tracés hérités de l'Antiquité.",
      status: "candidate",
    },
    thermal: {
      label: "Thermal",
      family: "patrimoine",
      weight: "precise",
      description: "Villes d'eaux, thermalisme et architecture de cure.",
      status: "candidate",
    },
    art_nouveau: {
      label: "Art nouveau",
      family: "patrimoine",
      weight: "rare",
      description: "Architecture et arts décoratifs Art nouveau.",
      status: "candidate",
    },
    vauban: {
      label: "Vauban",
      family: "patrimoine",
      weight: "rare",
      description: "Fortifications ou villes liées au système défensif de Vauban.",
      status: "candidate",
    },
    unesco: {
      label: "UNESCO",
      family: "patrimoine",
      weight: "precise",
      description: "Sites ou pratiques reconnus par l'UNESCO.",
      status: "candidate",
    },
    reconstruction: {
      label: "Reconstruction",
      family: "patrimoine",
      weight: "precise",
      description: "Bâti et urbanisme issus des reconstructions du XXe siècle.",
      status: "candidate",
    },
    colonial: {
      label: "Colonial",
      family: "patrimoine",
      weight: "precise",
      description: "Traces bâties, mémorielles ou urbaines liées à l'histoire coloniale.",
      status: "candidate",
    },
    moderniste: {
      label: "Moderniste",
      family: "patrimoine",
      weight: "precise",
      description: "Architecture moderne, villas, équipements ou urbanisme du XXe siècle.",
      status: "candidate",
    },
  },

  ambiance: {
    melancolique: {
      label: "Mélancolique",
      family: "ambiance",
      weight: "generic",
      description: "Atmosphère de retrait, de mémoire ou de douceur triste.",
      status: "active",
    },
    sauvage: {
      label: "Sauvage",
      family: "ambiance",
      weight: "standard",
      description: "Impression de nature peu domestiquée ou de territoire indocile.",
      status: "active",
    },
    spectaculaire: {
      label: "Spectaculaire",
      family: "ambiance",
      weight: "standard",
      description: "Paysage ou lieu à fort impact visuel.",
      status: "active",
    },
    crepusculaire: {
      label: "Crépusculaire",
      family: "ambiance",
      weight: "precise",
      description: "Atmosphère de lumière basse, de fin de journée ou de tension douce.",
      status: "active",
    },
    rude: {
      label: "Rude",
      family: "ambiance",
      weight: "precise",
      description: "Territoire perçu comme dur, froid, austère ou exigeant.",
      status: "active",
    },
    romantique: {
      label: "Romantique",
      family: "ambiance",
      weight: "standard",
      description: "Ambiance de paysage sensible, littéraire ou contemplatif.",
      status: "candidate",
    },
    mysterieux: {
      label: "Mystérieux",
      family: "ambiance",
      weight: "standard",
      description: "Territoire associé à l'énigme, aux légendes ou à l'étrangeté.",
      status: "candidate",
    },
    lumineux: {
      label: "Lumineux",
      family: "ambiance",
      weight: "standard",
      description: "Paysages ou villes marqués par une clarté forte.",
      status: "candidate",
    },
    austere: {
      label: "Austère",
      family: "ambiance",
      weight: "precise",
      description: "Ambiance sobre, minérale, froide ou peu décorative.",
      status: "candidate",
    },
    vertical: {
      label: "Vertical",
      family: "ambiance",
      weight: "precise",
      description: "Impression de hauteur, falaise, pente ou skyline.",
      status: "candidate",
    },
    horizontal: {
      label: "Horizontal",
      family: "ambiance",
      weight: "precise",
      description: "Paysages plats, ouverts, de plaine ou de littoral bas.",
      status: "candidate",
    },
    tropical_humide: {
      label: "Tropical humide",
      family: "ambiance",
      weight: "rare",
      description: "Atmosphère chaude, végétale et humide des territoires tropicaux.",
      status: "candidate",
    },
    aride: {
      label: "Aride",
      family: "ambiance",
      weight: "precise",
      description: "Sensation de sécheresse, lumière dure ou végétation rare.",
      status: "candidate",
    },
  },

  culture: {
    cinema: {
      label: "Cinéma",
      family: "culture",
      weight: "standard",
      description: "Lieux de tournage, imaginaires filmiques ou culture visuelle.",
      status: "active",
    },
    culture_pop: {
      label: "Culture populaire",
      family: "culture",
      weight: "standard",
      description: "Références connues du grand public, médias ou icônes populaires.",
      status: "active",
    },
    culture_celte: {
      label: "Culture celte",
      family: "culture",
      weight: "precise",
      description: "Références bretonnes ou celtiques dans les paysages et récits.",
      status: "active",
    },
    michelin: {
      label: "Michelin",
      family: "culture",
      weight: "rare",
      description: "Culture industrielle et populaire associée à Michelin.",
      status: "active",
    },
    litterature: {
      label: "Littérature",
      family: "culture",
      weight: "standard",
      description: "Écrivains, œuvres ou paysages littéraires.",
      status: "candidate",
    },
    bd: {
      label: "Bande dessinée",
      family: "culture",
      weight: "precise",
      description: "Culture de la bande dessinée, festivals ou lieux associés.",
      status: "candidate",
    },
    musique: {
      label: "Musique",
      family: "culture",
      weight: "standard",
      description: "Scènes, festivals, traditions ou lieux musicaux.",
      status: "candidate",
    },
    gastronomie: {
      label: "Gastronomie",
      family: "culture",
      weight: "standard",
      description: "Produits, cuisines ou traditions alimentaires territoriales.",
      status: "candidate",
    },
    vin: {
      label: "Vin",
      family: "culture",
      weight: "precise",
      description: "Vignobles, caves, paysages ou cultures viticoles.",
      status: "candidate",
    },
    thermalisme: {
      label: "Thermalisme",
      family: "culture",
      weight: "precise",
      description: "Culture des cures, villes d'eaux et sociabilités thermales.",
      status: "candidate",
    },
    surf: {
      label: "Surf",
      family: "culture",
      weight: "rare",
      description: "Culture des vagues et littoraux de glisse.",
      status: "candidate",
    },
    spatial: {
      label: "Spatial",
      family: "culture",
      weight: "rare",
      description: "Activités, lieux ou imaginaires liés à l'espace.",
      status: "candidate",
    },
  },

  histoire: {
    memoire: {
      label: "Mémoire",
      family: "histoire",
      weight: "standard",
      description: "Territoire marqué par le souvenir, les traces ou les commémorations.",
      status: "active",
    },
    guerre: {
      label: "Guerre",
      family: "histoire",
      weight: "standard",
      description: "Sites, paysages ou récits liés aux conflits.",
      status: "active",
    },
    cathare: {
      label: "Cathare",
      family: "histoire",
      weight: "rare",
      description: "Héritage, imaginaire ou sites liés au catharisme.",
      status: "active",
    },
    prehistoire: {
      label: "Préhistoire",
      family: "histoire",
      weight: "precise",
      description: "Grottes, traces humaines anciennes ou paysages préhistoriques.",
      status: "active",
    },
    resistance: {
      label: "Résistance",
      family: "histoire",
      weight: "precise",
      description: "Lieux et récits liés à la Résistance.",
      status: "candidate",
    },
    frontiere: {
      label: "Frontière",
      family: "histoire",
      weight: "standard",
      description: "Territoire marqué par une limite nationale, culturelle ou militaire.",
      status: "candidate",
    },
    royal: {
      label: "Royal",
      family: "histoire",
      weight: "precise",
      description: "Sites ou récits liés à la monarchie et aux pouvoirs princiers.",
      status: "candidate",
    },
    gaulois: {
      label: "Gaulois",
      family: "histoire",
      weight: "rare",
      description: "Sites, peuples ou récits liés à la Gaule.",
      status: "candidate",
    },
    esclavage: {
      label: "Esclavage",
      family: "histoire",
      weight: "rare",
      description: "Mémoires et traces liées à l'esclavage et aux sociétés coloniales.",
      status: "candidate",
    },
    bagne: {
      label: "Bagne",
      family: "histoire",
      weight: "rare",
      description: "Sites et mémoires liés aux bagnes coloniaux ou pénitentiaires.",
      status: "candidate",
    },
    debarquement: {
      label: "Débarquement",
      family: "histoire",
      weight: "precise",
      description: "Lieux liés aux débarquements et à la Libération.",
      status: "candidate",
    },
  },

  economie: {
    industriel: {
      label: "Industriel",
      family: "economie",
      weight: "standard",
      description: "Usines, bassins de production ou culture industrielle.",
      status: "active",
    },
    minier: {
      label: "Minier",
      family: "economie",
      weight: "precise",
      description: "Mines, terrils, bassins extractifs ou mémoire minière.",
      status: "active",
    },
    ouvrier: {
      label: "Ouvrier",
      family: "economie",
      weight: "precise",
      description: "Culture sociale, mémoire du travail ou villes ouvrières.",
      status: "active",
    },
    naval: {
      label: "Naval",
      family: "economie",
      weight: "precise",
      description: "Chantiers, arsenaux, construction ou culture navale.",
      status: "active",
    },
    portuaire: {
      label: "Portuaire",
      family: "economie",
      weight: "standard",
      description: "Ports, quais, docks ou activités de façade maritime.",
      status: "active",
    },
  },

  singularite: {
    iconique: {
      label: "Iconique",
      family: "singularite",
      weight: "standard",
      description: "Lieu ou territoire immédiatement reconnaissable.",
      status: "active",
    },
    insolite: {
      label: "Insolite",
      family: "singularite",
      weight: "standard",
      description: "Caractère inattendu, étrange ou difficile à classer.",
      status: "candidate",
    },
    extreme: {
      label: "Extrême",
      family: "singularite",
      weight: "rare",
      description: "Record, position limite ou intensité territoriale forte.",
      status: "candidate",
    },
    isole: {
      label: "Isolé",
      family: "singularite",
      weight: "precise",
      description: "Éloignement, faible accessibilité ou retrait géographique.",
      status: "candidate",
    },
    frontalier: {
      label: "Frontalier",
      family: "singularite",
      weight: "standard",
      description: "Territoire structuré par la proximité d'une frontière.",
      status: "candidate",
    },
    ultramarin: {
      label: "Ultramarin",
      family: "singularite",
      weight: "precise",
      description: "Territoire français situé outre-mer.",
      status: "candidate",
    },
    metropolitain_dense: {
      label: "Métropolitain dense",
      family: "singularite",
      weight: "precise",
      description: "Territoire urbain dense, fortement métropolisé.",
      status: "candidate",
    },
    periurbain: {
      label: "Périurbain",
      family: "singularite",
      weight: "standard",
      description: "Territoire d'entre-deux entre ville dense et espaces ruraux.",
      status: "candidate",
    },
  },

  meta: {
    rural: {
      label: "Rural",
      family: "meta",
      weight: "generic",
      description: "Marqueur large de faible densité, campagnes ou ruralité.",
      status: "active",
    },
    underdog: {
      label: "Underdog",
      family: "meta",
      weight: "standard",
      description: "Tag de méta-jeu pour les territoires sous-estimés ou rarement joués.",
      status: "active",
    },
    inattendu: {
      label: "Inattendu",
      family: "meta",
      weight: "standard",
      description: "Choix territorial surprenant mais défendable.",
      status: "candidate",
    },
    rare: {
      label: "Rare",
      family: "meta",
      weight: "rare",
      description: "Territoire ou caractéristique peu fréquente dans la base.",
      status: "candidate",
    },
  },
};
